name: "SEED-Bench 2"
task_num: 1
json_path: /home/projects/shimon/Collaboration/seedbench/SEED-Bench_v2_level1_2_3.json
image_root: /home/projects/shimon/Collaboration/seedbench/SEED-Bench-2-image
eval_method: ppl
display_name: "${task.name}"